version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    image: trueosiris/minecraft-skyfactory4
    ports:
      - "25565:25565"
    volumes:
      - "C:/dockervolumes/skyfactory/:/data"
    environment:
      EULA: "TRUE"
    restart: always

volumes:
  mc: {}